import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Poems",
  description: "Explore all public dosti poems generated by the community.",
  alternates: { canonical: "/poems" },
};

export default function PoemsLayout({ children }: { children: React.ReactNode }) {
  return children;
}


